import './globals.css';
import { Poppins, Bruno_Ace, Figtree } from "next/font/google";
import type { Metadata } from "next";
import ClientLayout from './client-layout.tsx/page';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});

const brunoAce = Bruno_Ace({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}