import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
// import { LayoutProps } from "framer-motion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps{
  children: ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
